### ISSUE TITLE
Add CMI and MyWarps

### ISSUE THREAD

**Issue by The-patik** [Avankziar/BungeeTeleportManager#10]
Hi! Can you please add support to import homes and warps from CMI and to import warps from MyWarps? :) Thank you

**Comment by Avankziar** [comment]
Hi!
Yes I can add support [CMI](https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/) and [MyWarps](https://www.spigotmc.org/resources/mywarp.34974/). (Correct me, if the links are not the plugin which you mean^^)

But unfortunately this will take some time to implement. Please be patient^^

**Comment by The-patik** [comment]
https://dev.bukkit.org/projects/mywarp

This mywarp, cmi is right, thank you :)

**Comment by Avankziar** [comment]
Hi again^^,
can you provide a example of how the plugins store the homes & warps (Mysql)? You would do me a big help^^(So i dont setup the plugins myself :D)
Pictures of the table Structure should be enough^^

**Comment by nhanledev** [comment]
Hello, I am planing to mirage CMI homes into this plugin. I can provide sample content of CMI homes in MYSQL if you are still need them :)

**Comment by Avankziar** [comment]
@nhanledev yes you can^^

**Comment by nhanledev** [comment]
CMI saves homes in mysql column called `Homes`

![image](https://user-images.githubusercontent.com/28459250/211135126-bf243ec2-cc7e-48c8-aea8-0418f16bb5cf.png)

Sample data:

`home_name%%world_name:3705.59:13.0:-2859.77:-61.8:12.18`

If I am not wrong it is `home name %% world name : X : Y : Z : Yaw : Pitch`

Below is a sample took from a user that has multiple homes

`ikawn%%world_resource:1700.8:-36.0:1231.68:23.64:-5.79;ioanwr%%world_resource:1543.69:0.0:1713.0:22.19:113.89;thapcuop%%world_resource:2153.04:80.0:2133.21:31.16:-53.89;knaw%%world_resource:4553.52:-23.0:-3725.3:51.43:-23.38;iawr%%world_resource:-1002.67:13.0:-2378.75:3.6:-70.43;khunglong%%world_resource:-4477.45:77.0:1547.61:28.9:-97.52;famkl%%world_resource:-2033.68:207.0:-4080.95:45.88:139.84;cauca%%world_resource:2312.44:64.0:724.69:52.42:-1.7`

**Comment by Avankziar** [comment]
@nhanledev thanks^^

**Comment by Avankziar** [comment]
@nhanledev I have written the import for mysql CMI Homes. Is inclueded in the new Update. But i havent tested it, because of problems on my end^^. So if bug shown up, open a issue^^.

**Comment by Avankziar** [comment]
@nhanledev Update for CMI Homes are out. Not Tested, have no data to work with. So I close this. Open a another up, if there are bugs^^
