### ISSUE TITLE
Hide server name on homes/homelist and allow to create new-line in message

### ISSUE THREAD

**Issue by nhanledev** [Avankziar/BungeeTeleportManager#12]
Hello,

Thank you for the great plugin. Due to the native of the source code, I can not build or find any way to compile the source you've provided. So, I have some suggestions:
- Allow to turn off displaying SERVER NAME on `/homes` screen. I think players don't need to know about whatever server they are playing, and admins often use schematical names like server1, server 2, and that makes the home list look not so as pretty as it should be.
- Allow using `\n` character in language file to make a newline for message decoration.

That's it.

**Comment by Avankziar** [comment]
Hello @nhanledev,
Well, the first thing with the servername, I can write it on my list. The second thing with \n, I have to do some research to find out how and if it is possible to implement this "on the fly".

**Comment by Avankziar** [comment]
@nhanledev,
I have checked the "\n" thing. there is a problem, if a message is called from the language files, the character "\n" is not simply tangible. I look into this a hour and found no answer.
But I have a proposal, normally for hover etc. I using "~!~" as a seperator for a new line. And I have also tested this.
Are you ok, with that?

**Comment by nhanledev** [comment]
Hello, 

I am so sorry that I don't know much about how the newline \n thing works, but it helps to create multiple-line messages to players, and I see many plugins do that (I am personally using CMI and TradeSystem to create eye-candy requests that send to players. I don't use the hover much so I did not test that function, mine are just Accept and Deny as simple as it is.

It is okay that my suggestion can not be implemented due to limited function of your chat formatter. I think it would be very nice to have, not a must :D

**Comment by Avankziar** [comment]
@nhanledev 
Ok. As such, \n as ~!~ is implemented. Also the Server (and world) at /homes can be set false in the config.
With this I close the issue. Comes everything in the next update^^.

**Comment by nhanledev** [comment]
Hello,
I test the `~!~` character as line separator in tpa/tpahere message but it does not work.
I use like this:
```
&r𬮱 ~!~&r            &b&lBạn nhận được yêu cầu dịch chuyển ~!~&r            %player% muốn ghé thăm bạn.~!~&r           &r'
```

But it turns out as
![image](https://user-images.githubusercontent.com/28459250/219429585-b843949c-0767-4d10-99e5-33f281f00583.png)

**Comment by Avankziar** [comment]
Yes, my error, have forgotten some lines.
I'll catch up, thanks for the report^^
