### ISSUE TITLE
Make the "|" character between "accept" and "deny" translatable

### ISSUE THREAD

**Issue by nhanledev** [Avankziar/BungeeTeleportManager#13]
Hello,

I have a suggestion that I would like the "|" character between the "accept" and "deny" message to be translatable.
Currently it is hardcoded as "|" with white color.

![image](https://user-images.githubusercontent.com/28459250/219418734-e163eadf-262b-41af-b26c-ab13874bf4fc.png)

I want to remake into this

![image](https://user-images.githubusercontent.com/28459250/219418886-cd48ef5e-1a5c-48a1-8cd0-8e957760879c.png)

**Comment by Avankziar** [comment]
Is noted, coded an comes in the next update.^^

**Comment by Avankziar** [comment]
@nhanledev 
I should add that the line (Even just the ones that go to others) where the accept and reject is in does not allow line wrapping, because of the message parser. Sry.

**Comment by nhanledev** [comment]
> @nhanledev I should add that the line (Even just the ones that go to others) where the accept and reject is in does not allow line wrapping, because of the message parser. Sry.

Yes, sadly I need newline in those tpa/tpahere location. But it's ok I will try another design. TYSM for the very fast support <3
