### ISSUE TITLE
Warp Point

### ISSUE THREAD

**Issue by Dartume** [Avankziar/BungeeTeleportManager#4]
Hallo ich versuche einen Warp Punkt zu erstellen leider geht dieses nicht.

https://pastebin.com/3keSCihZ

Home´s können erstllt werden und werden in der Datenbank gespeichert.

**Comment by Avankziar** [comment]
@Dartume danke für das melden des Bugs, ich werde den beheben und gleich die Fixversion hochladen.
Bei weitern Fragen hierzu, eröffne den Thread einfach neu.
