### ISSUE TITLE
Chat Meldungen

### ISSUE THREAD

**Issue by Dartume** [Avankziar/BungeeTeleportManager#5]
Hallo,

bei einem Teleport oder Warp bekommen ALLE Spieler auf dem Server die Meldung  HOME CheckForbidden und HOME isntForbidden also alle Spieler beommen diese Nachricht nicht nur der welcher sich Teleportiert oder den Warp ausführt.

Kann man in der config eventuell diese nachricht auch ganz deaktivieren ?

**Comment by Avankziar** [comment]
Also um den Fehler zu definieren:
Bei /warp oder /tp, bekommen alle Spieler auf dem Server die Nachricht "&cAuf diesem Server dürfen keine Homes erstellt werden!"

Richtig?

**Comment by Dartume** [comment]
Hallo,
habe noch mal weiter getestet,
man erstellt sich auf Server A Welt 1 und auf Server B Welt 1 ein home(oder warp) Teleportiert sich da hin und her kommen diese beiden Nachrichten an Alle spieler die Online sind nicht nur an dem der /Home oder /warp nuzt.
man erstellt sich auf Server A Welt 1 und auf Welt 2 ein home(oder warp) Teleportiert sich da hin und her Keine Nachricht

**Comment by Avankziar** [comment]
ok, ich gehe der sache nach.

Nutzt ihr die neueste Version?
Welche genau Chatausgabe kommt?

**Comment by Dartume** [comment]
Wir verwenden Version 5-7 und es kommt erst die Meldung HOME CheckForbidden und direkt 
danach HOME isntForbidden

**Comment by Avankziar** [comment]
Das hört sich nach einer Debug nachricht an.

**Comment by Dartume** [comment]
auszug aus dem Proxy Log
[14:21:44] [Netty Worker IO Thread #11/INFO] [BungeeTeleportManager]: HOME CheckForbidden
[14:21:44] [Netty Worker IO Thread #11/INFO] [BungeeTeleportManager]: HOME IsntForbidden

**Comment by Dartume** [comment]
server Seitig ist kein Debug an und in der Config von BungeeTeleport habe ich jetzt nix für Debug gefunden.

**Comment by Avankziar** [comment]
Nee, von euch aus ist auch nix falsch^^
Ich mach in testversionen die an, um den code zu debuggen.
Muss ich mal suchen, wo der angeblieben ist^^

**Comment by Dartume** [comment]
meine Spieler haben gefragt ob eventuell in Zukunft ne Gui für die Homes gibt ? ;-)

**Comment by Avankziar** [comment]
Guis sind etwas für spätere versionen. Ich wollte erstmal die eigentlichen Mechaniken implementieren. Danach kann man darüber nachdenken^^.

**Comment by Dartume** [comment]
ich hätte da noch was wenn man /TPA name macht bekommt der andere die Chat nachricht man Klickt drauf und es kommt nur deine TpaIgnorierungsliste:
und dann etwas später die anfrage ist abgelaufen aber die Person wird nicht Teleportiert.
Bei /TPAHere das selbe.
auf /tpaccept geht nicht.

**Comment by Avankziar** [comment]
Ich bräuchte von dir mal dann die commands.yml von btm

**Comment by Dartume** [comment]
https://pastebin.com/3rdkm8bv

**Comment by Avankziar** [comment]
Das mit dem /tpa habe ich gefixt, bei der nächsten version sollte das behoben sein.
Jedoch der andere Fehler finde ich nicht. Ich habe nun mehrfach den Code durchgeschaut. Also die einzige Empfehlung erstmal, neue Sprachdatein generieren lassen.

Sonst, nunja, such ich mal weiter.

**Comment by Dartume** [comment]
Ok sobald die neu version download bar ist werde ich dann auch gleich einmal die Sprachdateien reseten

**Comment by Dartume** [comment]
TPA geht jetzt die Sprachdatei habe ich gelöscht und neu generieren lassen, Leider kommt die meldung immer noch (wenn du das Testen willst oder schneller informationen braucht Skrypta.net ist unser Server und auch TS adresse)
