### ISSUE TITLE
RandamTeleport

### ISSUE THREAD

**Issue by Dartume** [Avankziar/BungeeTeleportManager#6]
Hallo,

beim ausführen der Funktion Randam Teleport Stürzt der Zielserver ab.

https://pastebin.com/1Q2TuaYf

**Comment by Avankziar** [comment]
Was hast du in deine config reingeschrieben?
Und danke fürs melden.

**Comment by Dartume** [comment]
Hier mal meine Config vom Start Server Ziel ist bis auf den Namen Identisch
https://pastebin.com/kBw0eGqx

**Comment by Avankziar** [comment]
Also, das Problem hier liegt bei der Berechnung des y Wertes.
Der Server sucht sich die Max-Y raus aus deiner Angabe (das ist 254) und zählt bis deiner Min angabe runter (das ist 50)
scheinbar ist das etwas zu viel rechenaufwand.
Ich probiere das anderes zu berechnen, mal schauen ob es geht.

**Comment by Avankziar** [comment]
In der neuen 5-12 Version, ist die veränderte Rechenlogik enthalten. Falls keine probleme mehr entstehen, schließe bitte einfach das Issue. (Falls nicht mache ich das innerhalb der nächsten Tage^^)
