### ISSUE TITLE
Feature: Sichere Teleport Location

### ISSUE THREAD

**Issue by JeffHD** [Avankziar/BungeeTeleportManager#7]
Hey ich habe ein Feature was ich mir wünschen würde.

Situation:
Ich habe ein Home gesetzt und jemand anderes baut diesen nun zu. Wenn ich mich nun zu meinem Home teleportiere würde ich nun in der Wand ersticken.

Mein Vorschlag wäre ein simpler Test ob, die angegebene Position sicher ist. Ich habe dies bei meinem Plugins mit der [LocationUtil.class](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/utils/LocationUtil.java) von EssentialsX gelöst und war immer sehr zufrieden. Falls es nicht schon diese Funktion gibt und ich sie nur übersehen habe wäre es toll diese Option (vllt. auch nur als Optionale) in den Einstellungen zu finden.

Danke schonmal

**Comment by Avankziar** [comment]
Grüße,

eine nette Idee, jedoch die Umsetzung wird sich sehr schwierig gestalten.
Innerhalb eines Servers ist das noch relative einfach, jedoch serverübergreifend wird es problematisch, weil man zuerst auf den anderen Server verschoben wird und dann zu dieser Location teleportiert wird. (Deshalb gibt es ja die Effekte, welche vorher und nach dem eigentlichen Teleport angewendet werden können^^.

Aber ich schau mal, was eventuell gehen würde.

**Comment by JeffHD** [comment]
Ich habe jetzt nicht komplett in den Code geschaut aber die Koordinaten aus zB den tp Befehl werden ja sicher vom Server an Bungee und dann zum Ziel Server gesendet und dieser Teleportiert einen ja zur gewünschten Koordinate. Sollte dann es doch eigentlich möglich sein die Koordinaten am Ziel Server dann überprüfen lassen, ob diese sicher sind oder gegebenenfalls geändert werden müssen. Anstatt auf einem Server der das dann berechnet, berechnet dies dann der Ziel Server.

**Comment by Avankziar** [comment]
Das ist schon möglich keine Frage, aber dann werden die Stimmen schnell laut, warum man "zuerst" auf Location xx landet und dann teleportiert wird (Weil das Plugin ja Zeit braucht, um festzustellen OB da was ist oder nicht).
Wenn man es optional macht, wie du es vorschlägst, wäre es wahrscheinlich am sinnigsten.

**Comment by JeffHD** [comment]
Ja optional würde es funktionieren. Alternative wäre sonst die Koordinate vor dem teleportieren schon zum Server zu senden und verarbeiten zu lassen. Dann diese zwischenspeichern bis der Spieler joint. Was einem auch Zeit verschaffen würde, sich den Cooldown zunutze zu machen und in der Zeit die Berechnung machen zu lassen

**Comment by Avankziar** [comment]
Also ich habe mich entschieden, dies zu testen (Gemeint ist aber "nur" Spieler zu Location xxx. Spieler zu Spieler ist immer ein Risiko. Dazu kann sich der Zielspieler ja immer noch bewegen^^). Zum nächsten VersionsUpdate (was ich nun anfange zu coden), werde ich das einbauen und Optional als Config Wert zulassen.

Falls das aller Erwartung nach Bungeeübergreifen nicht "einwandfrei" funktioniert, werde ich das in diesem Teil fallen lassen.

Grüße Avan
